# Generated by Django 3.1.7 on 2021-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeofEmpries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('expansion', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('build_time', models.DateTimeField(auto_now_add=True)),
                ('reload_time', models.DateTimeField(auto_now_add=True)),
                ('attack_delay', models.IntegerField()),
                ('movement_rate', models.IntegerField()),
                ('line_of_sight', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('range', models.CharField(max_length=50)),
                ('attack', models.IntegerField()),
                ('armor', models.CharField(max_length=50)),
                ('attack_bonus', models.CharField(max_length=50)),
                ('armor_bonus', models.CharField(max_length=50)),
                ('search_radius', models.IntegerField()),
                ('accuracy', models.CharField(max_length=50)),
                ('blast_radius', models.IntegerField()),
            ],
        ),
    ]
